apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: fattfatt/auth-service:hermes
        resources:
          limits:
            memory: "1280Mi"
            cpu: "500m"
        ports:
        - containerPort: 3001
        env:
          - name: SERVICE_NAME
            valueFrom:
              secretKeyRef:
                name: auth-service-secret
                key: SERVICE_NAME
          - name: PORT
            valueFrom:
              secretKeyRef:
                name: auth-service-secret
                key: PORT
          - name: ACCOUNT_SERVICE_URL
            valueFrom:
              secretKeyRef:
                name: auth-service-secret
                key: ACCOUNT_SERVICE_URL
          - name: ACCESS_TOKEN_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-service-secret
                key: ACCESS_TOKEN_SECRET
          - name: ACCESS_TOKEN_EXPIRATION
            valueFrom:
              secretKeyRef:
                name: auth-service-secret
                key: ACCESS_TOKEN_EXPIRATION
          - name: REFRESH_TOKEN_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-service-secret
                key: REFRESH_TOKEN_SECRET
          - name: REFRESH_TOKEN_EXPIRATION
            valueFrom:
              secretKeyRef:
                name: auth-service-secret
                key: REFRESH_TOKEN_EXPIRATION
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: LoadBalancer
  selector:
    app: auth-service
  ports:
  - port: 3001
    targetPort: 3001            
